devtools::install_github("nldoc/nlrx")
install.packages("sf")
install.packages('furrr', repos='http://cran.us.r-project.org')
install.packages('magrittr')
install.packages("dplyr", repos='http://cran.us.r-project.org')
